//
// Created by ranhe on 08.03.2026.
//

#ifndef VOXELFRUITNINJA_CONFIG_H
#define VOXELFRUITNINJA_CONFIG_H

const int WINDOW_WIDTH  = 2944;
const int WINDOW_HEIGHT = 1840;

#endif //VOXELFRUITNINJA_CONFIG_H

